# Generated by Django 6.0.4 on 2026-06-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasenia',
            new_name='contraseña',
        ),
    ]
