# Generated by Django 6.0.4 on 2026-06-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_categorias_clientes_productos_proveedores_usuarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contrasenia',
            new_name='contraseña',
        ),
    ]
